### ISSUE TITLE
uwp does not work from the REPL

### ISSUE THREAD

**Issue by hgwood** [Microsoft/node-uwp#13]
```
21:54 $ node
> var uwp = require("uwp")
undefined
> uwp.projectNamespace("Windows")
undefined
> Windows
Error: Windows. (0x80000011): an unexpected failure occurred while trying to obtain metadata information
   at objectToString (util.js:706:3)
   at isRegExp (util.js:673:3)
   at formatValue (util.js:353:3)
   at inspect (util.js:107:3)
   at self.writer (repl.js:337:7)
   at finish (repl.js:458:9)
   at defaultEval (repl.js:269:5)
   at bound (domain.js:280:5)
   at runBound (domain.js:293:5)
   at Anonymous function (repl.js:412:7)
```

This only occurs when in the REPL. Running files works. So it's not really an issue, but I thought it could be mentioned somewhere, probably in the readme.

**Comment by jianchun** [comment]
Thanks for reporting all the issues! Looks we trigger an exception while trying to "stringify" a UWP object (I tested and the basic functionality works in REPL). We'll look into this.
