### ISSUE TITLE
Error trying to install the module

### ISSUE THREAD

**Issue by DracotMolver** [Microsoft/node-uwp#29]
I've got this nex error: **(I'm using windows 10)**
```sh
  uwp.cc
  win_delay_load_hook.cc
..\src\uwp.cc(74): error C2065: 'JsErrorCode': undeclared identifier [C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(74): error C2146: syntax error: missing ';' before identifier 'err' [C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(74): error C2065: 'err': undeclared identifier [C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(75): error C2061: syntax error: identifier 'JsProjectionCallback' [C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(77): error C3481: 'jsCallback': lambda capture variable not found [C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(77): error C3481: 'jsContext': lambda capture variable not found [C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(77): error C3493: 'jsCallback' cannot be implicitly captured because no default capture mode has been specified [C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\
uwp\build\uwp.vcxproj]
..\src\uwp.cc(77): error C3493: 'jsContext' cannot be implicitly captured because no default capture mode has been specified [C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\u
wp\build\uwp.vcxproj]
..\src\uwp.cc(74): error C3861: 'JsSetProjectionEnqueueCallback': identifier not found [C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(82): error C2065: 'err': undeclared identifier [C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(82): error C2065: 'JsNoError': undeclared identifier [C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(104): error C3861: 'JsProjectWinRTNamespace': identifier not found [C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(104): error C2065: 'JsNoError': undeclared identifier [C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\uwp\build\uwp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\diego\Documents\ElectronJS Projects\Soube\node_modules\uwp
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN ajv-keywords@2.0.1-beta.2 requires a peer of ajv@>=5.0.4-beta.0 but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "uwp" "--save-dev"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! uwp@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! Failed at the uwp@1.0.2 install script 'node-gyp rebuild'.

**Comment by Brahko** [comment]
I'm having the same issue. Any resolution?

**Comment by DracotMolver** [comment]
I moved to this repository [https://github.com/NodeRT/NodeRT](url)
