### ISSUE TITLE
Cannot install module

### ISSUE THREAD

**Issue by MarkTiedemann** [Microsoft/node-uwp#33]
Any help would be much appreciated.

```
λ ver
Microsoft Windows [Version 10.0.16299.492]

λ node -p -e "process.version + '-' + process.jsEngine"
v10.1.0-chakracore

λ npm install uwp@1.0.2
(node:11844) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

> uwp@1.0.2 install C:\dev\example\node_modules\uwp
> node-gyp rebuild


C:\dev\example\node_modules\uwp>if not defined npm_config_node_gyp (node "C:\Users\wwwma\AppData\Local\nvs\chakracore\10.1.0\x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\wwwma\AppData\Local\nvs\chakracore\10.1.0\x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  uwp.cc
  win_delay_load_hook.cc
C:\dev\example\node_modules\nan\nan.h(138): warning C4005: 'TYPE_CHECK': macro redefinition (compiling source file ..\src\uwp.cc) [C:\dev\example\node_modules\uwp\build\uwp .vcxproj]
  C:\Users\wwwma\AppData\Local\nvs\chakracore\10.1.0\x64\sdk\deps\chakrashim\include\v8.h(88): note: see previous definition of 'TYPE_CHECK' (compiling source file ..\src\u
  wp.cc)
..\src\uwp.cc(75): error C2061: syntax error: identifier 'JsProjectionCallback' [C:\dev\example\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(77): error C3481: 'jsCallback': lambda capture variable not found [C:\dev\example\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(77): error C3481: 'jsContext': lambda capture variable not found [C:\dev\example\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(77): error C3493: 'jsCallback' cannot be implicitly captured because no default capture mode has been specified [C:\dev\example\node_modules\uwp\build\uwp.vcx proj]
..\src\uwp.cc(77): error C3493: 'jsContext' cannot be implicitly captured because no default capture mode has been specified [C:\dev\example\node_modules\uwp\build\uwp.vcxp roj]
..\src\uwp.cc(74): error C3861: 'JsSetProjectionEnqueueCallback': identifier not found [C:\dev\example\node_modules\uwp\build\uwp.vcxproj]
..\src\uwp.cc(104): error C3861: 'JsProjectWinRTNamespace': identifier not found [C:\dev\example\node_modules\uwp\build\uwp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack    at onExit (C:\Users\wwwma\AppData\Local\nvs\chakracore\10.1.0\x64\node_modules\npm\node_modules\node-gyp\lib\build.js:258:7)
gyp ERR! stack    at Reflect.apply (native code:0:0)
gyp ERR! stack    at emit (events.js:182:5)
gyp ERR! stack    at _handle.onexit (internal/child_process.js:235:7)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\wwwma\\AppData\\Local\\nvs\\chakracore\\10.1.0\\x64\\node.exe" "C:\\Users\\wwwma\\AppData\\Local\\nvs\\chakracore\\10.1.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\example\node_modules\uwp
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\example\package.json'
npm WARN example No description
npm WARN example No repository field.
npm WARN example No README data
npm WARN example No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uwp@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uwp@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wwwma\AppData\Roaming\npm-cache\_logs\2018-07-06T18_32_15_165Z-debug.log
```

**Comment by imcody** [comment]
Is there any update to this? I am facing this same issue...
