### ISSUE TITLE
How can I use it for NW.js  ?

### ISSUE THREAD

**Issue by sudhakar3697** [Microsoft/node-uwp#34]
How can I use it for NW.js  ?

Basically rebuilding it for other JS Engines (V8)

**Comment by sudhakar3697** [comment]
I get this Error


C:\Users\Sudhakar_r_R\Desktop\RS5_Tr\UWP-WinRT-Usage>nw-gyp build --target=0.34.5
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.6.3
gyp info using node@11.2.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  uwp.cc
c:\users\sudhakar_r_r\.nw-gyp\0.34.5\deps\v8\include\v8.h(4388): warning C4996: 'v8::WasmCompiledModule::CallerOwnedBuffer': was declared dep
recated [C:\Users\Sudhakar_r_R\Desktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
  c:\users\sudhakar_r_r\.nw-gyp\0.34.5\deps\v8\include\v8.h(4372): note: see declaration of 'v8::WasmCompiledModule::CallerOwnedBuffer'
c:\users\sudhakar_r_r\.nw-gyp\0.34.5\deps\v8\include\v8.h(4473): warning C4996: 'v8::WasmCompiledModule::CallerOwnedBuffer': was declared dep
recated [C:\Users\Sudhakar_r_R\Desktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
  c:\users\sudhakar_r_r\.nw-gyp\0.34.5\deps\v8\include\v8.h(4372): note: see declaration of 'v8::WasmCompiledModule::CallerOwnedBuffer'
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(74): error C2065: 'JsErrorCode': undeclared identifier [C:\Users\Sudhakar_r_R
\Desktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(74): error C2146: syntax error: missing ';' before identifier 'err' [C:\Users
\Sudhakar_r_R\Desktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(74): error C2065: 'err': undeclared identifier [C:\Users\Sudhakar_r_R\Desktop
\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(75): error C2061: syntax error: identifier 'JsProjectionCallback' [C:\Users\S
udhakar_r_R\Desktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(77): error C3481: 'jsCallback': lambda capture variable not found [C:\Users\S
udhakar_r_R\Desktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(77): error C3481: 'jsContext': lambda capture variable not found [C:\Users\Su
dhakar_r_R\Desktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(77): error C3493: 'jsCallback' cannot be implicitly captured because no defau
lt capture mode has been specified [C:\Users\Sudhakar_r_R\Desktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(77): error C3493: 'jsContext' cannot be implicitly captured because no defaul
t capture mode has been specified [C:\Users\Sudhakar_r_R\Desktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(74): error C3861: 'JsSetProjectionEnqueueCallback': identifier not found [C:\
Users\Sudhakar_r_R\Desktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(82): error C2065: 'err': undeclared identifier [C:\Users\Sudhakar_r_R\Desktop
\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(82): error C2065: 'JsNoError': undeclared identifier [C:\Users\Sudhakar_r_R\D
esktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(104): error C3861: 'JsProjectWinRTNamespace': identifier not found [C:\Users\
Sudhakar_r_R\Desktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(104): error C2065: 'JsNoError': undeclared identifier [C:\Users\Sudhakar_r_R\
Desktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
c:\users\sudhakar_r_r\desktop\rs5_tr\uwp-winrt-usage\src\uwp.cc(103): warning C4996: 'v8::String::Value::Value': was declared deprecated [C:\
Users\Sudhakar_r_R\Desktop\RS5_Tr\UWP-WinRT-Usage\build\uwp.vcxproj]
  c:\users\sudhakar_r_r\.nw-gyp\0.34.5\deps\v8\include\v8.h(3015): note: see declaration of 'v8::String::Value::Value'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Sudhakar_r_R\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:261:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sudhakar_r_R\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "build" "--target=0.34.5"
gyp ERR! cwd C:\Users\Sudhakar_r_R\Desktop\RS5_Tr\UWP-WinRT-Usage
gyp ERR! node -v v11.2.0
gyp ERR! nw-gyp -v v3.6.3
gyp ERR! not ok
